baseURL = 'http://example.org/'
languageCode = 'ru-RU'
theme = 'anubis'
title = 'Урал Хасанов'
summaryLength = 35

[pagination]
pagerSize = 5

[params]
author = "Ural Khasanov personal page"
description = "Programming. Modern Perl. DevOps. System administration."
dateFormat = "Jan 2 2006"
mainSections = [ "posts" ]
paginationSinglePost = false
#readMore = false
#readNextPosts = 2
style = "auto"
customCSS = ["css/my.css"]
copyCodeButton = false
#rssAsSocialIcon = true
mathjax = false

googleAnalytics = ""
disqusShortname = ""

[[params.social]]
id = "github"
url = "https://github.com/uralm1/uralm1.github.io"

[menu]

[[menu.main]]
identifier = "home"
name = "Главная"
url = "/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Индекс"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "cv"
name = "Моё резюме"
url = "/cv"
weight = 10

[markup.goldmark.renderer]
unsafe = true
